version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  proxy:
    build: ./proxy
    image: zsuffazs/proxy-nginx
    container_name: proxy-nginx
    ports:
      - "8000"
    networks:
      - prodnetwork
    depends_on:
      - site1
      - site2

  site1:
    build: ./site1
    image: zsuffazs/proxy-site1
    container_name: site1
    ports:
      - "8001"
    environment:
      - VIRTUAL_HOST=site1.local
    networks:
      - prodnetwork
      
  site2:
    build: ./site2
    image: zsuffazs/proxy-site2
    container_name: site2
    ports:
      - "8002"
    environment:
      - VIRTUAL_HOST=site2.local
    networks:
      - prodnetwork
      