version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 proxy:
  build: ./proxy
  image: zsuffazs/proxy-nginx
  ports:
    - "80:80"
  networks:
    - prodnetwork
  depends_on:
    - site1
    - site2

 site1:
  build: ./site1
  image: zsuffazs/proxy-site1
  ports:
    - "8001:80"
  networks:
    - prodnetwork

 site2:
  build: ./site2
  image: zsuffazs/proxy-site2
  ports:
    - "8002:80"
  networks:
    - prodnetwork
